name: Docker Image CI

on:
  push:
    branches: [ main ]

  push:
    tags: ['*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: make build

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish the Docker image
      run: make push-github-registry

    - name: Publish release tag
      if: env.HEAD_TAG != ''
      run: make build tag=$(${{env.HEAD_TAG}}) && make push-github-registry tag=$(${{env.HEAD_TAG}})
